/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categorias/': RouteRecordInfo<
      '/categorias/',
      '/categorias',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categorias/[Categoria]': RouteRecordInfo<
      '/categorias/[Categoria]',
      '/categorias/:Categoria',
      { Categoria: ParamValue<true> },
      { Categoria: ParamValue<false> },
      | never
    >,
    '/receita/[Id]': RouteRecordInfo<
      '/receita/[Id]',
      '/receita/:Id',
      { Id: ParamValue<true> },
      { Id: ParamValue<false> },
      | never
    >,
    '/receitas/[Nome]': RouteRecordInfo<
      '/receitas/[Nome]',
      '/receitas/:Nome',
      { Nome: ParamValue<true> },
      { Nome: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/categorias/index.vue': {
      routes:
        | '/categorias/'
      views:
        | never
    }
    'src/pages/categorias/[Categoria].vue': {
      routes:
        | '/categorias/[Categoria]'
      views:
        | never
    }
    'src/pages/receita/[Id].vue': {
      routes:
        | '/receita/[Id]'
      views:
        | never
    }
    'src/pages/receitas/[Nome].vue': {
      routes:
        | '/receitas/[Nome]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
